version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
      
    depends_on:
      - backend

    environment:
      - REACT_APP_API_URL=http://backend:9002
      - REACT_APP_SOCKET_URL=ws://backend:8080

  backend:
    build:
      context: ./backend
    ports:
      - "9002:9002"
      - "8080:3000"
